# base image
FROM python:3.12

# setup working directory in container
WORKDIR /app

# copy all the files to app directory
COPY . /app/

# command to run on container start
CMD [ "python", "main.py" ]
