#base image file
FROM python:3.12

#current working directory for container
WORKDIR /app

#copy files to the working directory
COPY . /app/

#commands to run as container start

CMD [ "python", "main.py" ]